[package]
name = "simple_pdf_generator_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "simple_pdf_generator_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.33"
serde = "1.0.187"
serde_json = "1.0.105"
syn = { version = "2.0.29", features = ["full"] }
